# Generated by Django 5.0.6 on 2024-06-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(default='', max_length=100)),
                ('chat_id', models.IntegerField(default=0)),
                ('full_message', models.TextField()),
                ('name', models.CharField(max_length=512)),
                ('grade', models.CharField(max_length=50)),
                ('stack', models.CharField(max_length=512)),
                ('instruments', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('is_regular_staff', models.CharField(max_length=50)),
                ('full_or_part_time', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('contact', models.TextField()),
                ('comment', models.TextField(default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('mark', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectVacanciesWithSpecialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.specialists')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citizenship', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=200)),
                ('type', models.BooleanField()),
                ('is_urgent', models.BooleanField()),
                ('chat_name', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
                ('grade', models.CharField(max_length=50)),
                ('stack', models.CharField(max_length=512)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('is_regular_staff', models.CharField(max_length=50)),
                ('full_or_part_time', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('specialists', models.ManyToManyField(through='core_app.ConnectVacanciesWithSpecialists', to='core_app.specialists')),
            ],
        ),
        migrations.AddField(
            model_name='connectvacancieswithspecialists',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.vacancies'),
        ),
    ]
