# Generated by Django 5.0.6 on 2024-06-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='chat_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
