# Generated by Django 5.0.6 on 2024-06-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_vacancies_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectvacancieswithspecialists',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.specialists'),
        ),
        migrations.AlterField(
            model_name='connectvacancieswithspecialists',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.vacancies'),
        ),
    ]
