# Generated by Django 5.0.6 on 2024-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_connectvacancieswithspecialists_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancies',
            name='contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancies',
            name='full_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
