# Generated by Django 5.0.6 on 2024-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_vacancies_comment_vacancies_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='full_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='instruments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='full_message',
            field=models.TextField(default=''),
        ),
    ]
