# Generated by Django 5.0.6 on 2024-06-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_specialists_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='chat_id',
            new_name='chatid',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='chat_name',
            new_name='chatname',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='full_message',
            new_name='fullmessage',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='is_urgent',
            new_name='isurgent',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='full_or_part_time',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='is_regular_staff',
        ),
        # migrations.RemoveField(
        #     model_name='vacancies',
        #     name='name',
        # ),
        migrations.RemoveField(
            model_name='vacancies',
            name='stack',
        ),
    ]
