# Generated by Django 5.0.6 on 2024-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_rename_chat_id_vacancies_chatid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='grade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
