# Generated by Django 5.0.6 on 2024-06-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_vacancies_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='chatid',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='chatname',
            new_name='chat_name',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='fullmessage',
            new_name='full_message',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='isurgent',
            new_name='is_urgent',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='full_or_part_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='instruments',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='is_regular_staff',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='stack',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='full_or_part_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='is_regular_staff',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='stack',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='citizenship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='rate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='term',
            field=models.CharField(default='', max_length=200),
        ),
    ]
