# Generated by Django 5.0.6 on 2024-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_rename_chatid_vacancies_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='mark',
            field=models.IntegerField(default=-1),
        ),
    ]
