# Generated by Django 5.0.6 on 2024-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_rename_chatid_vacancies_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='chat_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='citizenship',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='contact',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='experience',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='full_message',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='full_or_part_time',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='grade',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='instruments',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='is_regular_staff',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='location',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='rate',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='stack',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='term',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
