# Generated by Django 5.0.6 on 2024-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_merge_20240707_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
