# Generated by Django 5.0.6 on 2024-07-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_remove_vacancies_name_alter_vacancies_chat_name_and_more'),
        ('core_app', '0010_remove_vacancies_name'),
    ]

    operations = [
    ]
