# Generated by Django 5.0.6 on 2024-07-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_specialists_date_alter_vacancies_date'),
        ('core_app', '0011_merge_20240707_2145'),
    ]

    operations = [
    ]
